version: '3.8'
name: honest-be

services:
  honest-be:
    build: .
    container_name: honest-be
    restart: always
    environment:
      - PROFILES=${PROFILES}
      - ADDITIONAL_PROFILES=docker,local-dc
      - CONFIG_SERVER_DOMAIN=${CONFIG_SERVER_DOMAIN}
      - DB_USER=postgres
      - DB_PASSWORD=1234
    networks:
      - dc-net

networks:
  dc-net:
    external: true