version: '3.8'
name: honest-be

services:
  honest-be:
    image: ${IMAGE}
    container_name: honest-be
    restart: always
    environment:
      - PROFILES=${PROFILES}
      - CONFIG_SERVER_DOMAIN=${CONFIG_SERVER_DOMAIN}
    networks:
      - dc-net

networks:
  dc-net:
    external: true