spring:
  application:
    name: honest-be
  datasource:
    url: jdbc:postgresql://localhost:5432/honest
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true