server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/honest
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: honest-be
  config:
    import: configserver:http://127.0.0.1:8888
  cloud:
    config:
      fail-fast: true
    compatibility-verifier:
      enabled: false

ru:
  honest:
    prop: ${MY_PROP}

