server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: never

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG


spring:
  profiles:
    active: ${PROFILES:}
    include: ${ADDITIONAL_PROFILES:}
  cloud:
    config:
      enabled: false
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://pg:5432/honest
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: honest-be

mybatis:
  config-location: classpath:/mybatis‑config.xml
  mapper-locations: classpath*:mappers/*.xml
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true

honest:
  last-card-text: ${LAST_CARD_TEXT}
  sub-path: /honest-be
  gpt:
    service: vse
    vse:
      api-key: ${GPT_API_KEY}
      model: ${GPT_MODEL}
    questions-gen:
      prompt-template: ${GPT_GEN_QUESTION_PROMPT_TEMPLATE}
      error-message: ${GPT_QUESTION_ERROR_MESSAGE}
      system-message: ${GPT_SYSTEM_MESSAGE}

---

spring:
  config:
    activate:
      on-profile: local,test
  datasource:
    url: jdbc:postgresql://localhost:5432/honest

honest:
  sub-path: /

---

spring:
  config:
    import: configserver:${CONFIG_SERVER_DOMAIN}
    activate:
      on-profile: docker
  cloud:
    config:
      fail-fast: true
      enabled: true

springdoc:
  swagger-ui:
    url: /honest-be/api-docs
    config-url: /honest-be/api-docs/swagger-config