server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: never

spring:
  cloud:
    config:
      enabled: false
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/honest
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: honest-be

mybatis:
  config-location: classpath:/mybatis‑config.xml
  mapper-locations: classpath*:mappers/*.xml
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger

honest:
  last-card-text: ${LAST_CARD_TEXT}
---

spring:
  config:
    activate:
      on-profile: local,test

---

spring:
  config:
    import: configserver:http://127.0.0.1:8888
    activate:
      on-profile: prod,stage
  cloud:
    config:
      fail-fast: true
      enabled: true
